image: backoffice:latest

services:
    - docker:dind

stages:
    - deploy
    - clean

before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

deploy:
    stage: deploy
    tags:
        - deploying
    script:
        - echo "Building image.."
        #- docker build -t backoffice:latest .
        # - docker build -t laruno/backoffice .
        - echo "create network"
        #- docker network create net
        - docker-compose up -d
        # - docker-compose up --build
        - docker run --rm --name nginx-dummy -e VIRTUAL_HOST=backoffice.laruno.id -e LETSENCRYPT_HOST=backoffice.laruno.id -e VIRTUAL_PORT=80 --network net -d nginx:latest
    only:
        - master

clean:
    stage: clean
    tags:
        - cleaning
    script:
        - docker stop nginx-dummy
        - docker-compose down
        - docker run --name nextcloud --network net -e VIRTUAL_HOST="backoffice.laruno.id" -e LETSENCRYPT_HOST="backoffice.laruno.id" -d nextcloud:19.0.2
        # - docker container stop -f  laruno/backoffice || true && docker container rm -f  laruno/backoffice || true
        #- docker run -d -it -p 80:80/tcp --name backoffice laruno/backoffice:latest
        # - docker run -dt -p 8000:80 --name=backoffice laruno/backoffice:latest
        #- docker run -d -p 8000:8000 --name backoffice -d backoffice
        - docker image prune -f
        - docker container prune -f
    only:
        - master
