image: laruno/backoffice:latest

services:
    - docker:dind

stages:
    - build
    - deploy
    - publish

before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
    stage: build
    tags:
        - building
    script:
        - echo "Building image.."
        - docker build -t laruno/backoffice:latest --no-cache .
        - echo "Tagging image.."
        - docker tag laruno/backoffice:latest laruno/backoffice:latest
    only:
        - master

deploy:
    stage: deploy
    tags:
        - deploying
    script:
        - docker stop laruno/backoffice || true && docker rm laruno/backoffice || true
        - docker run -dit -p 8000:8000 laruno/backoffice:latest
        - docker image prune -f
        - docker container prune -f
    only:
        - master

publish:
    stage: publish
    tags:
        - publishing
    script:
        - echo "Publishing image.."
        - ls
        - cp -r build/* /var/www/backoffice.laruno.id
    only:
        - master
