image: laruno/backoffice:latest

services:
    - docker:dind

stages:
    - build
    - deploy

before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
    stage: build
    tags:
        - building
    script:
            #- docker stop $(docker ps | grep ":8000" | awk '{print $1}')
            #- docker rm $(docker ps | grep ":8000" | awk '{print $1}')
        - docker container prune -f
        - docker image prune -f
        - echo "Building image.."
        - docker build -t laruno/backoffice:latest --no-cache .
        - echo "Tagging image.."
        - docker tag laruno/backoffice:latest laruno/backoffice:latest
    only:
        - master

deploy:
    stage: deploy
    tags:
        - deploying
    script:
        - docker stop laruno/backoffice:latest || true && docker rm laruno/backoffice:latest || true
        - docker run -dt -p 8000:8000 laruno/backoffice:latest
        - docker image prune -f
        - docker container prune -f
        - docker cp backoffice:/app/backoffice /var/www/backoffice.laruno.id
    only:
        - master
