stages:
    - build
    - deploy

build:
    stage: build
    tags: 
        - publish
        - development
    script:
        - cp .env.example .env
        - echo "Building deploy package"
        - yarn install
        - yarn build
        - echo "Build successful"
    artifacts:
        expire_in: 1 hour
        paths:
            - build
         
deploy_production:
    stage: deploy
    tags: 
      - deploy
      - production
    script:
        - echo "Deploying to server"
        - cp -rv build/* /var/www/backoffice.laruno.id/
        - echo "Deployed"
    environment:
        name: production
        url: https://backoffice.laruno.id
    only:
        - master

