image: backoffice:latest

services:
    - docker:dind

stages:
    - deploy
    - clean

before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

deploy:
    stage: deploy
    tags:
        - deploying
    script:
        - echo "Building image.."
        #- docker build -t backoffice:latest .
        # - docker build -t laruno/backoffice .
        - docker-compose up -d
        # - docker-compose up --build
        - echo "Tagging image.."
        - docker tag laruno/backoffice:latest laruno/backoffice:latest
    only:
        - master

clean:
    stage: clean
    tags:
        - cleaning
    script:
        - docker container stop -f  laruno/backoffice || true && docker container rm -f  laruno/backoffice || true
        - docker run -d -it -p 80:80/tcp --name backoffice laruno/backoffice:latest
        # - docker run -dt -p 8000:80 --name=backoffice laruno/backoffice:latest
        #- docker run -d -p 8000:8000 --name backoffice -d backoffice
        - docker image prune -f
        - docker container prune -f
    only:
        - master
