cache:
    paths:
        - node_modules/
        
stages:
    - build
    - test
    - deploy
    
build:
    image: node:10
    stage: build
    script:
        - npm run build
    artifacts:
        expire_in: 1 hour
        paths:
            - ./build
    only:
        - master
        
test:
    image: node:10
    stage: test
    script:
        - echo "Running react test suite......"
        - npm run test
    only:
        - master
        
deploy:
    image: node:10
    only:
        refs:
            - master
    stage: deploy
    environment: production

    script:
        - echo "Deploying to server"
        - cp -rv build/* /var/www/backoffice.laruno.id