deploy:
  image: alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "USER_NAME@SERVER_IP"
    - echo "$SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no dev-apis@139.162.59.84 "cd ~; touch test.txt"