image: node:alpine
cache:
    paths:
        - node_modules/

deploy_production:
    only:
        refs:
            - master
    stage: deploy
    environment: production
    script:
        - ls
        - npm install
        - npm run build
        - cd build/
        - ls
        - sshpass -V
        - export SSHPASS=$USER_PASS
        - rsync -r --omit-dir-times -e "ssh -o StrictHostKeyChecking=no" . $USER_NAME@$SERVER_IP:/var/www/backoffice.laruno.id
