image: node:latest
cache:
    paths:
        - node_modules/
            
before_script:
    - apt-get update -qq && apt-get install -y -qq sshpass rsync

deploy_production:
    only:
        refs:
            - master
    stage: deploy
    environment: production
    script:
        - yarn install
        - yarn build
        - cd build/
        - ls
        - sshpass -V
        - export SSHPASS=$USER_PASS
        - rsync -r --omit-dir-times -e "ssh -o StrictHostKeyChecking=no" . $USER_NAME@$SERVER_IP:/var/www/backoffice.laruno.id
