version: "3.8"

services:
    nginx:
        build: "./nginx"
        container_name: "nginx"
        ports: 
           - "80:80"
           - "443:443"
        restart: always
        
    backoffice:
        build: ./
        ports: 
            - "8000:8000"